### ISSUE TITLE
Price of Anarchy

### ISSUE THREAD

**Issue by fszmit** [duszku/game_theory#4]
- general idea
- example
- bounding the price of anarchy

**Comment by duszku** [comment]
Implemented as follows:

- [2b32924](https://github.com/duszku/game_theory/commit/2b32924bc5a2a9568d9d7ff353b7741be84da9bc) - general idea
- [3f36fe1](https://github.com/duszku/game_theory/commit/3f36fe1b50f9528416edb3f5cf77c0e8fc94ed73) - example
- [a067009](https://github.com/duszku/game_theory/commit/a067009a553edf0e40ce7900be31d63d4a032624) - bounding
